# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: BoekSolutions.LibSync
PackageVersion: 1.2.4
InstallerType: inno
Scope: machine
ElevationRequirement: elevatesSelf
UpgradeBehavior: install
ReleaseDate: 2026-10-07
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/JohnBoek/boeksolutions.libsync-releases/releases/download/v1.2.4/LibSync-Setup.exe
    InstallerSha256: C31A62958357978FA7922A9C39F91BAFB5E2830D9AD6B443EC0782FDE90315E6
    ProductCode: "{6219A392-16B3-415A-AE12-A33BB0465824}_is1"
    AppsAndFeaturesEntries:
      - DisplayName: LibSync version 1.2.4
        Publisher: BoekSolutions
        ProductCode: "{6219A392-16B3-415A-AE12-A33BB0465824}_is1"
ManifestType: installer
ManifestVersion: 1.12.0
